function runPGfit(jsn_settings)
% Run The shape-appearance model on "imported" scans
% For help, type:
% runPG --help
%__________________________________________________________________________
% Copyright (C) 2017 Wellcome Trust Centre for Neuroimaging

% John Ashburner
% $Id$

if nargin<1 || (ischar(jsn_settings) && (strcmp(jsn_settings,'--help') || strcmp(jsn_settings,'--h')))
    show_instructions
    return
end

settings    = spm_jsonread(jsn_settings);
train_file  = settings.train;
filenames   = settings.input;
latent_file = settings.output;

res = load(train_file);
[pth,~,~] = fileparts(train_file);
if isa(res.Wv,'file_array')
    [~,nam,ext]  = fileparts(res.Wv.fname);
    res.Wv.fname = fullfile(pth,[nam ext]);
end

if isa(res.Wa,'file_array')
    [~,nam,ext]  = fileparts(res.Wa.fname);
    res.Wa.fname = fullfile(pth,[nam ext]);
end

t_settings     = res.s;
t_settings.nit = t_settings.maxit*t_settings.nit;

% Get data
dat      = struct('f',filenames,'z',zeros(res.s.Kv,1));
for n=1:numel(dat)
    dat(n).f = char(dat(n).f{:});
end

%t_settings.verbose = true;

% Run the fitting
[dat,~] = UpdateAllZ(dat,res.mu,res.Wa,res.Wv,res.noise,res.RegZ,t_settings);

% Save the latent variable expectations
Z  = cat(2,dat.z);
N  = size(Z,2);
Zc = cell(N,1);
for n=1:N
    Zc{n} = Z(:,n);
end
spm_jsonwrite(latent_file,Zc);


function show_instructions
disp('Usage: runPGfit settings.jsn');
disp(' ');
disp('Input images must first be imported using SPM12''s Segment tool, giving a series of rc1*.nii and rc2*.nii files.');
disp('The settings.jsn is a JSON file with the following general structure:');
disp('{"train":"trainXXX.mat",                     % Name of mat file generated by training.');
disp(' "output":"output.jsn",                      % Name of output file containing estimated latent variables.');
disp(' "input":[["rc1SCAN01.nii","rc2SCAN01.nii"],');
disp('          ["rc1SCAN02.nii","rc2SCAN02.nii"],');
disp('          ["rc1SCAN03.nii","rc2SCAN03.nii"],');
disp('                  :                :        ');
disp('          ["rc1SCANXX.nii","rc2SCANXX.nii"]]}');
disp(' ');

